version: '3.8'

services:
  app:
    build:
      context: ./app
    container_name: node-app
    ports:
      - "3000:3000"
    networks:
      - appnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet:
